### PR TITLE
Migrated to use version 5 of 'hsyslog`

### PR DESCRIPTION
**Pull request by qrilka**

### CODE REVIEW

**Comment by qrilka** [comment]
@Jonplussed are you still maintaining this package?

**Comment by k-bx** [comment]
@Jonplussed can you please add me and Kirill as maintainers? My email is k-bx@k-bx.com on Hackage. Thanks.

**Comment by Jonplussed** [comment]
@k-bx I've added you as a maintainer; sorry for the delay in replying!

**Comment by k-bx** [comment]
@Jonplussed no problem at all! Thanks for adding me

**Pull request merged**
